# Generated by Django 3.0 on 2019-12-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_fitur', '0003_auto_20191212_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='profile',
            name='socmed',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
